# Generated by Django 5.0.3 on 2024-04-01 10:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_filter_name', models.CharField(max_length=50)),
                ('air_filter_type', models.CharField(max_length=50)),
                ('air_filter_brand', models.CharField(max_length=50)),
                ('air_filter_description', models.TextField()),
                ('air_filter_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Air filters',
                'verbose_name_plural': 'Air filters',
                'db_table': 'air_filters',
                'ordering': ['air_filter_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrakeFluid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake_fluid_name', models.CharField(max_length=50)),
                ('brake_fluid_type', models.CharField(max_length=50)),
                ('brake_fluid_brand', models.CharField(max_length=50)),
                ('brake_fluid_description', models.TextField()),
                ('brake_fluid_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Brake fluids',
                'verbose_name_plural': 'Brake fluids',
                'db_table': 'brake_fluids',
                'ordering': ['brake_fluid_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrakePad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake_pad_name', models.CharField(max_length=50)),
                ('brake_pad_type', models.CharField(max_length=50)),
                ('brake_pad_brand', models.CharField(max_length=50)),
                ('brake_pad_description', models.TextField()),
                ('brake_pad_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Brake pads',
                'verbose_name_plural': 'Brake pads',
                'db_table': 'brake_pads',
                'ordering': ['brake_pad_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CabinFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_filter_name', models.CharField(max_length=50)),
                ('cabin_filter_type', models.CharField(max_length=50)),
                ('cabin_filter_brand', models.CharField(max_length=50)),
                ('cabin_filter_description', models.TextField()),
                ('cabin_filter_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Cabin filters',
                'verbose_name_plural': 'Cabin filters',
                'db_table': 'cabin_filters',
                'ordering': ['cabin_filter_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_location', models.CharField(max_length=50)),
                ('brand_year_of_establishment', models.DateField()),
                ('brand_description', models.TextField()),
                ('brand_logo_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brand_website_link', models.TextField()),
            ],
            options={
                'verbose_name': 'Car brands',
                'verbose_name_plural': 'Car brands',
                'db_table': 'car_brands',
                'ordering': ['brand_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=50)),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=2)),
                ('engine_hp', models.IntegerField()),
                ('engine_number_of_cylinders', models.IntegerField()),
                ('engine_number_of_valves', models.IntegerField()),
                ('engine_fuel_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Car engines',
                'verbose_name_plural': 'Car engines',
                'db_table': 'car_engines',
                'ordering': ['engine_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_owner', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100)),
                ('company_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('company_first_address', models.CharField(max_length=100)),
                ('company_second_address', models.CharField(max_length=100)),
                ('company_address_google_map', models.TextField()),
            ],
            options={
                'verbose_name': 'Company information',
                'verbose_name_plural': 'Company information',
                'db_table': 'company_info',
                'ordering': ['company_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coolant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolant_name', models.CharField(max_length=50)),
                ('coolant_type', models.CharField(max_length=50)),
                ('coolant_color', models.CharField(max_length=50)),
                ('coolant_brand', models.CharField(max_length=50)),
                ('coolant_description', models.TextField()),
                ('coolant_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Coolants',
                'verbose_name_plural': 'Coolants',
                'db_table': 'coolants',
                'ordering': ['coolant_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EngineOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil_name', models.CharField(max_length=50)),
                ('engine_oil_type', models.CharField(max_length=50)),
                ('engine_oil_density', models.CharField(max_length=50)),
                ('engine_oil_tolerances', models.CharField(max_length=50)),
                ('engine_oil_brand', models.CharField(max_length=50)),
                ('engine_oil_description', models.TextField()),
                ('engine_oil_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Engine oils',
                'verbose_name_plural': 'Engine oils',
                'db_table': 'engine_oils',
                'ordering': ['engine_oil_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FuelFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_filter_name', models.CharField(max_length=50)),
                ('fuel_filter_type', models.CharField(max_length=50)),
                ('fuel_filter_brand', models.CharField(max_length=50)),
                ('fuel_filter_description', models.TextField()),
                ('fuel_filter_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Fuel filters',
                'verbose_name_plural': 'Fuel filters',
                'db_table': 'fuel_filters',
                'ordering': ['fuel_filter_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OilFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_filter_name', models.CharField(max_length=50)),
                ('oil_filter_brand', models.CharField(max_length=50)),
                ('oil_filter_description', models.TextField()),
                ('oil_filter_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Oil filters',
                'verbose_name_plural': 'Oil filters',
                'db_table': 'oil_filters',
                'ordering': ['oil_filter_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransmissionOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_oil_name', models.CharField(max_length=50)),
                ('transmission_oil_type', models.CharField(max_length=50)),
                ('transmission_oil_atf_type', models.CharField(max_length=50)),
                ('transmission_oil_brand', models.CharField(max_length=50)),
                ('transmission_oil_description', models.TextField()),
                ('transmission_oil_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Transmission oils',
                'verbose_name_plural': 'Transmission oils',
                'db_table': 'transmission_oils',
                'ordering': ['transmission_oil_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarEngineAirFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.airfilter')),
                ('car_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carengine')),
            ],
            options={
                'verbose_name': 'Car engine - air filters',
                'verbose_name_plural': 'Car engine - air filters',
                'db_table': 'car_engine_air_filters',
                'ordering': ['car_engine'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_years_of_production', models.CharField(max_length=20)),
                ('model_body_type', models.CharField(max_length=50)),
                ('model_wheel_drive_type', models.CharField(max_length=50)),
                ('model_description', models.TextField()),
                ('model_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models_info', to='application.carbrand')),
            ],
            options={
                'verbose_name': 'Car models',
                'verbose_name_plural': 'Car models',
                'db_table': 'car_models',
                'ordering': ['model_name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carengine',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_engines_info', to='application.carmodel'),
        ),
        migrations.CreateModel(
            name='CarModelBrakeFluid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake_fluid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.brakefluid')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carmodel')),
            ],
            options={
                'verbose_name': 'Car model - brake fluids',
                'verbose_name_plural': 'Car model - brake fluids',
                'db_table': 'car_model_brake_fluids',
                'ordering': ['car_model'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarModelBrakePad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake_pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.brakepad')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carmodel')),
            ],
            options={
                'verbose_name': 'Car model - brake pads',
                'verbose_name_plural': 'Car model - brake pads',
                'db_table': 'car_model_brake_pads',
                'ordering': ['car_model'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarModelCabinFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.cabinfilter')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carmodel')),
            ],
            options={
                'verbose_name': 'Car model - cabin filters',
                'verbose_name_plural': 'Car model - cabin filters',
                'db_table': 'car_model_cabin_filters',
                'ordering': ['car_model'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_type', models.CharField(max_length=20)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_transmissions_info', to='application.carmodel')),
            ],
            options={
                'verbose_name': 'Car transmissions',
                'verbose_name_plural': 'Car transmissions',
                'db_table': 'car_transmissions',
                'ordering': ['transmission_type'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carbrand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brands_info', to='application.companyinfo'),
        ),
        migrations.CreateModel(
            name='CarEngineCoolant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carengine')),
                ('coolant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.coolant')),
            ],
            options={
                'verbose_name': 'Car engine - coolants',
                'verbose_name_plural': 'Car engine - coolants',
                'db_table': 'car_engine_coolants',
                'ordering': ['car_engine'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarEngineEngineOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carengine')),
                ('engine_oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.engineoil')),
            ],
            options={
                'verbose_name': 'Car engine - engine oils',
                'verbose_name_plural': 'Car engine - engine oils',
                'db_table': 'car_engine_engine_oils',
                'ordering': ['car_engine'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarEngineFuelFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carengine')),
                ('fuel_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.fuelfilter')),
            ],
            options={
                'verbose_name': 'Car engine - fuel filters',
                'verbose_name_plural': 'Car engine - fuel filters',
                'db_table': 'car_engine_fuel_filters',
                'ordering': ['car_engine'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarEngineOilFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.carengine')),
                ('oil_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.oilfilter')),
            ],
            options={
                'verbose_name': 'Car engine - oil filters',
                'verbose_name_plural': 'Car engine - oil filters',
                'db_table': 'car_engine_oil_filters',
                'ordering': ['car_engine'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarTransmissionTransmissionOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.cartransmission')),
                ('transmission_oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.transmissionoil')),
            ],
            options={
                'verbose_name': 'Car transmission - transmission oils',
                'verbose_name_plural': 'Car transmission - transmission oils',
                'db_table': 'car_transmission_transmission_oils',
                'ordering': ['car_transmission'],
                'managed': True,
            },
        ),
    ]
